apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: my-network-attachment4
  namespace: default
  annotations:
    "k8s.v1.cni.cncf.io/resourceName": "openshift.io/multus-additional-macvlan-network"
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "my-network-attachment4",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "whereabouts",
            "datastore": "kubernetes",
            "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
            "range": "192.168.5.1/24",
            "log_file" : "/tmp/whereabouts.log",
            "log_level" : "debug"
          }
        }
      ]
    }

