apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: my-network-attachment
  namespace: default
  annotations:
    "k8s.v1.cni.cncf.io/resourceName": "openshift.io/multus-additional-macvlan-network"
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "my-network-attachment",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "host-local",
            "subnet": "192.168.3.0/24",
            "rangeStart": "192.168.3.10",
            "rangeEnd": "192.168.3.200",
            "gateway": "192.168.3.1"
          }
        },
        {
          "name": "mytuning",
          "type": "tuning",
          "sysctl": {
                  "net.core.somaxconn": "500",
                  "net.ipv4.conf.IFNAME.arp_filter": "1"
          }
        }
      ]
    }
