apiVersion: v1
kind: Pod
metadata:
  name: testpod4
  namespace: kube-system
  annotations:
    k8s.v1.cni.cncf.io/networks: default/my-network-attachment3, default/my-network-attachment4
  labels:
    app: my-app  
spec:
  containers:
  - name: testpod4
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
